###
# Copyright (c) 2015-2017 Mainflux
#
# Mainflux is licensed under an Apache license, version 2.0 license.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

version: "3.7"

networks:
  agent-net:
    driver: bridge

services:
  jaeger:
    image: jaegertracing/all-in-one:1.38.0
    container_name: mainflux-jaeger
    ports:
      - ${AGENT_JAEGER_PORT}:${AGENT_JAEGER_PORT}/udp
      - ${AGENT_JAEGER_FRONTEND}:${AGENT_JAEGER_FRONTEND}
      - ${AGENT_JAEGER_COLLECTOR}:${AGENT_JAEGER_COLLECTOR}
      - ${AGENT_JAEGER_CONFIGS}:${AGENT_JAEGER_CONFIGS}
    networks:
      - agent-net

