version: "3.7"

networks:
  cocos-base-net:
    driver: bridge

volumes:
  cocos-computations-db-volume:
  cocos-datasets-db-volume:
  cocos-clients-db-volume:

services:

# CoCoS services
  computations-db:
    image: postgres:13.3-alpine
    container_name: cocos-computations-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${COCOS_COMPUTATIONS_DB_USER}
      POSTGRES_PASSWORD: ${COCOS_COMPUTATIONS_DB_PASS}
      POSTGRES_DB: ${COCOS_COMPUTATIONS_DB}
    networks:
      - cocos-base-net
    volumes:
      - cocos-computations-db-volume:/var/lib/postgresql/data

  computations:
    image: cocos/computations:${COCOS_RELEASE_TAG}
    container_name: cocos-computations
    depends_on:
      - computations-db
      - clients
    restart: on-failure
    environment:
      COCOS_COMPUTATIONS_LOG_LEVEL: ${COCOS_COMPUTATIONS_LOG_LEVEL}
      COCOS_COMPUTATIONS_DB_HOST: computations-db
      COCOS_COMPUTATIONS_DB_PORT: ${COCOS_COMPUTATIONS_DB_PORT}
      COCOS_COMPUTATIONS_DB_USER: ${COCOS_COMPUTATIONS_DB_USER}
      COCOS_COMPUTATIONS_DB_PASS: ${COCOS_COMPUTATIONS_DB_PASS}
      COCOS_COMPUTATIONS_DB: ${COCOS_COMPUTATIONS_DB}
      COCOS_COMPUTATIONS_HTTP_PORT: ${COCOS_COMPUTATIONS_HTTP_PORT}
      COCOS_COMPUTATIONS_AUTH_GRPC_URL: clients:${UV_CLIENTS_GRPC_PORT}
      COCO_COMPUTATIONS_AUTH_GRPC_TIMEOUT: ${UV_CLIENTS_GRPC_TIMEOUT}
    ports:
      - ${COCOS_COMPUTATIONS_HTTP_PORT}:${COCOS_COMPUTATIONS_HTTP_PORT}
    networks:
      - cocos-base-net

  datasets-db:
    image: postgres:13.3-alpine
    container_name: cocos-datasets-db
    restart: on-failure
    environment:
      POSTGRES_USER: ${COCOS_DATASETS_DB_USER}
      POSTGRES_PASSWORD: ${COCOS_DATASETS_DB_PASS}
      POSTGRES_DB: ${COCOS_DATASETS_DB}
    networks:
      - cocos-base-net
    volumes:
      - cocos-datasets-db-volume:/var/lib/postgresql/data

  datasets:
    image: cocos/datasets:${COCOS_RELEASE_TAG}
    container_name: cocos-datasets
    depends_on:
      - datasets-db
      - clients
    restart: on-failure
    environment:
      COCOS_DATASETS_LOG_LEVEL: ${COCOS_DATASETS_LOG_LEVEL}
      COCOS_DATASETS_DB_HOST: datasets-db
      COCOS_DATASETS_DB_PORT: ${COCOS_DATASETS_DB_PORT}
      COCOS_DATASETS_DB_USER: ${COCOS_DATASETS_DB_USER}
      COCOS_DATASETS_DB_PASS: ${COCOS_DATASETS_DB_PASS}
      COCOS_DATASETS_DB: ${COCOS_DATASETS_DB}
      COCOS_DATASETS_HTTP_PORT: ${COCOS_DATASETS_HTTP_PORT}
      COCOS_DATASETS_AUTH_GRPC_URL: clients:${UV_CLIENTS_GRPC_PORT}
      COCOS_DATASETS_AUTH_GRPC_TIMEOUT: ${UV_CLIENTS_GRPC_TIMEOUT}
    ports:
      - ${COCOS_DATASETS_HTTP_PORT}:${COCOS_DATASETS_HTTP_PORT}
    networks:
      - cocos-base-net
  clients-db:
    image: postgres:13.3-alpine
    container_name: cocos-clients-db
    restart: on-failure
    expose:
      - ${UV_CLIENTS_DB_PORT}
    environment:
      POSTGRES_USER: ${UV_CLIENTS_DB_USER}
      POSTGRES_PASSWORD: ${UV_CLIENTS_DB_PASS}
      POSTGRES_DB: ${UV_CLIENTS_DB}
    networks:
      - cocos-base-net
    command: -p ${UV_CLIENTS_DB_PORT}
    volumes:
      - cocos-clients-db-volume:/var/lib/postgresql/data

  clients:
    image: ultraviolet/clients:${MF_RELEASE_TAG}
    container_name: cocos-clients
    depends_on:
      - clients-db
    restart: on-failure
    expose:
      - ${UV_CLIENTS_GRPC_PORT}
    environment:
      UV_CLIENTS_LOG_LEVEL: ${UV_CLIENTS_LOG_LEVEL}
      UV_CLIENTS_DB_HOST: ${UV_CLIENTS_DB_HOST}
      UV_CLIENTS_DB_PORT: ${UV_CLIENTS_DB_PORT}
      UV_CLIENTS_DB_USER: ${UV_CLIENTS_DB_USER}
      UV_CLIENTS_DB_PASS: ${UV_CLIENTS_DB_PASS}
      UV_CLIENTS_DB: ${UV_CLIENTS_DB}
      UV_CLIENTS_DB_SSL_MODE: ${UV_CLIENTS_DB_SSL_MODE}
      UV_CLIENTS_DB_SSL_CERT: ${UV_CLIENTS_DB_SSL_CERT}
      UV_CLIENTS_DB_SSL_KEY: ${UV_CLIENTS_DB_SSL_KEY}
      UV_CLIENTS_DB_SSL_ROOT_CERT: ${UV_CLIENTS_DB_SSL_ROOT_CERT}
      UV_CLIENTS_HTTP_PORT: ${UV_CLIENTS_HTTP_PORT}
      UV_CLIENTS_GRPC_PORT: ${UV_CLIENTS_GRPC_PORT}
      UV_CLIENTS_GRPC_TIMEOUT: ${UV_CLIENTS_GRPC_TIMEOUT}
      UV_CLIENTS_SERVER_CERT: ${UV_CLIENTS_SERVER_CERT}
      UV_CLIENTS_SERVER_KEY: ${UV_CLIENTS_SERVER_KEY}
    ports:
      - ${UV_CLIENTS_HTTP_PORT}:${UV_CLIENTS_HTTP_PORT}
      - ${UV_CLIENTS_GRPC_PORT}:${UV_CLIENTS_GRPC_PORT}
    networks:
      - cocos-base-net
