###
# Copyright (c) 2015-2017 Mainflux
#
# Mainflux is licensed under an Apache license, version 2.0 license.
# All rights not explicitly granted in the Apache license, version 2.0 are reserved.
# See the included LICENSE file for more details.
###

version: "3.7"

networks:
  docker_mainflux-base-net:
    external: true

services:
  manager:
    image: mainflux/manager:latest
    container_name: mainflux-manager
    restart: on-failure
    environment:
      CC_MANAGER_LOG_LEVEL: ${CC_MANAGER_LOG_LEVEL}
      CC_MANAGER_HTTP_PORT: ${CC_MANAGER_HTTP_PORT}
      CC_MANAGER_SERVER_CERT: ${CC_MANAGER_SERVER_CERT}
      CC_MANAGER_SERVER_KEY: ${CC_MANAGER_SERVER_KEY}
      CC_JAEGER_URL: ${CC_JAEGER_URL}
      CC_MANAGER_SECRET: ${CC_MANAGER_SECRET}
    ports:
      - ${CC_MANAGER_HTTP_PORT}:${CC_MANAGER_HTTP_PORT}
    networks:
      - docker_mainflux-base-net
